name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Checks
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Lcov
        run: sudo apt install lcov -y

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup Cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('deps/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: |
            /home/runner/.deno

      - name: Cache
        run: deno cache mod.ts

      - name: Lint
        continue-on-error: true
        run: deno lint

      - name: Format
        continue-on-error: true
        run: deno fmt --check

      - name: Type Check
        continue-on-error: true
        run: deno check mod.ts

      - name: Test
        run: deno test --parallel --coverage=cov_profile

      - name: Coverage
        run: |
          deno coverage cov_profile --lcov --output=cov_profile.lcov

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ### Code Coverage
          \`\`\`
          $(lcov --summary cov_profile.lcov)
          \`\`\`
          EOF

