name: Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Lcov
        run: sudo apt install lcov -y

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Lint
        continue-on-error: true
        run: deno lint

      - name: Format
        continue-on-error: true
        run: deno fmt --check

      - name: Type Check
        continue-on-error: true
        run: deno check mod.ts

      - name: Jsr
        run: npx jsr publish --dry-run

      - name: Test
        # Allow read is required to run resolve tests
        run: deno test --allow-read --parallel --coverage=cov_profile

      - name: Coverage
        run: |
          set -e -o pipefail
          deno coverage cov_profile --lcov --output=cov_profile.lcov

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ### Code Coverage
          \`\`\`
          $(lcov --summary cov_profile.lcov)
          \`\`\`
          EOF
